### ISSUE TITLE
Rewards (PRE + TACo) for transition month (December 2023) 

### ISSUE THREAD

**Issue by arjunhassard** [threshold-network/merkle-distribution#105]
- Stakers will be able to spin up TACo nodes in December, with a strong incentive to do so before the end of December (longer lock-up bonus deadline). They will receive the standard 3.5% yield pro rata – based on when they first authorize T tokens to TACo. If they are already operating a PRE node they will be able to get the full month's rewards (see below). 
- Stakers will continue to receive compensation for running a PRE node until Dec 31st, after which there will be no incentive to do so (PRE services will be folded into TACo). Running a PRE node after Dec 31st UTC 00:00 will not be compensated in any way. 
- Regardless of when a staker authorizes to TACo in December, once they have done so they may shut down their PRE node and continue to receive the full month's rewards.

**Comment by manumonti** [comment]
Done: #116 #118 #122 #126 #127 #128
