### ISSUE TITLE
Replace `transfer` with `transferFrom`

### ISSUE THREAD

**Issue by theref** [threshold-network/merkle-distribution#6]
The current plan is to transfer all rewards into the merkle-distribution contract, which then automatically sends rewards as they are claimed.
New proposal is to instead Authorize the merkle-distribution contract to spend from the DOA/council (up to total rewards). When a user claims, it then uses `transferFrom`.
If there are bugs in the merkle-distribution contract, we are not stuck with all the funds locked away.

**Comment by cygnusv** [comment]
This implies also introducing a new contract variable to store the location of the approved funds, i.e., the `from` address for the `transferFrom`. This can be initialized in the constructor.
